swagger: "2.0"
info:
  version: "1.0.0"
  title: "Poppy Server API Specification"

tags:
- name: "AppUI"
  description: "App UI service group serve for the client UI. This group of api should not cover by `Authorization`"

- name: "Authorization"
  description: "Authorization service group."

- name: "Menu"
  description: "Menu service group. Include `HomeMenu` and `HeadMenu`"

- name: "Org"
  description: "Org service group."

- name: "Role"
  description: "Role service group."

- name: "User"
  description: "User service group."

- name: "App"
  description: "App service group."

consumes:
  - "application/json"
  - "application/x-www-form-urlencoded"
produces:
  - "application/json"

schemes:
- "http"
- "https"

securityDefinitions:
  accessToken:
    type: apiKey
    name: Authorization
    in: header

definitions:
  LoginDto:
    type: object
    properties:
      userName:
        type: string
        example: root
      password:
        type: string
        example: "********"
      appNo:
        type: string
    required:
      - userName
      - password
      - appNo

  AppDomainUIInfoBo:
    type: object
    properties:
      appNo:
        type: string
      domain:
        type: string

  AppUIInfoBo:
    type: object
    properties:
      locale:
        type: string
      displayName:
         type: string
      icp:
        type: string
      status:
        type: string

  TwoFactorListBo:
    type: object
    properties:
      email:
        type:
          - string
          - "null"
      optKey:
        type:
          - string
          - "null"
paths:
  /api/v1/app-ui/domain-info/{domain}:
    get:
      tags:
        - "AppUI"
      summary: "Get app-domain entity by domain"
      description: "This API should be the first one API for client to get the AppNo by domain."
      parameters:
        - in: path
          name: domain
          default: "http%3A%2F%2Flocalhost%3A7001"
          description: "If this value is empty it will get the domain from the request"
          type: string
          required: true
      responses:
        "200":
          description: ""
          schema:
            $ref: "#/definitions/AppDomainUIInfoBo"

  /api/v1/app-ui/app-info/{appNo}:
    get:
      tags:
        - "AppUI"
      summary: "Get app-theme properties"
      description: "Get the app info before login"
      parameters:
        - in: path
          name: appNo
          type: string
          required: true
      responses:
        "200":
          schema:
            $ref: "#/definitions/AppUIInfoBo"
          description: ""

  /api/v1/app-ui/theme-info/{appNo}:
    get:
      tags:
        - "AppUI"
      summary: "Get app ui info"
      description: "Get the app ui info before login"
      parameters:
        - in: path
          name: appNo
          type: string
          required: true
      responses:
        "200":
          description: ""

  /api/v1/authorization/session-auth:
    post:
      tags:
        - "Authorization"
      summary: "Validate and get the login token."
      description: "Validate the login centennial and response the authorization token."
      parameters:
        - in: body
          name: loginDto
          required: true
          schema:
            $ref: "#/definitions/LoginDto"
      responses:
        "200":
          description: ""

  /api/v1/authorization/session:
    post:
      tags:
        - "Authorization"
      parameters:
        - in: header
          name: session-token
          required: true
          type: string
      responses:
        "200":
          description: ""

    delete:
      tags:
        - "Authorization"
      responses:
        "200":
          description: ""
      security:
        - accessToken: []

  /api/v1/authorization/two-factor:
    get:
      tags:
        - "Authorization"
      parameters:
        - in: query
          name: userNo
          type: string
          required: true
        - in: header
          name: session-token
          required: true
          type: string
      responses:
        "200":
          schema:
            $ref: "#/definitions/TwoFactorListBo"
          description: ""

      deprecated: false

  /api/v1/menu/home-menu:
    get:
      summary: "Get the app menu tree for current user"
      tags:
        - "Menu"
      responses:
        "200":
          description: ""
      security:
        - accessToken: []

  /api/v1/menu/head-menu:
    get:
      summary: "Get the app head icon for current user"
      tags:
        - "Menu"
      responses:
        "200":
          description: ""
      security:
        - accessToken: []

  /api/v1/org:
    get:
      summary: "Get org list for current user"
      tags:
        - "Org"
      responses:
        "200":
          description: ""
      security:
        - accessToken: []


      deprecated: false

externalDocs:
  description: "http://swagger.io"
  url: "http://swagger.io"
