swagger: "2.0"
info:
  version: "1.0.0"
  title: "Poppy Server API Specification"

tags:
- name: "Authorization"
  description: "Authenticate to `poppy server`"

- name: "org"
  description: "Everything about your Pets"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"

- name: "app"
  description: "Access to Petstore orders"

- name: "role"
  description: "Operations about user"
  externalDocs:
    description: "Find out more about our store"
    url: "http://swagger.io"

consumes:
  - "application/json"
produces:
  - "application/json"

schemes:
- "http"
- "https"

securityDefinitions:
  accessToken:
    type: "apiKey"
    name: "Authorization"
    in: "header"

definitions:
  LoginDto:
    properties:
      userName:
        type: string
        required: true
        example: root
      password:
        type: string
        required: true
        example: "********"
      domain:
        type: string
        required: true
        example: "http:/127.0.0.1:7001"

paths:
  /api/v1/session-auth:
    post:
      tags:
      - "Authorization"
      description: "authorize for create session"
      parameters:
      - in: "body"
        name: "loginDto"
        required: true
        schema:
          $ref: "#/definitions/LoginDto"
      responses:
        200:
          description: OK

  # /api/v1/session:
  #   post:
  #     tags:
  #     - "Authorization"
  #     description: "create session by authorize token"


externalDocs:
  description: "http://swagger.io"
  url: "http://swagger.io"
