webserver:
  port: 7001

static:
  prefix: /public

i18n:
  defaultLocale: en

redis:
  keyPrefix: 'poppy:'
  host: 106.14.147.173
  port: 6379

accessToken:
  maxAge: 1h
  autoKeepActive: true
  fingerPrintOptions:
    userAgent: true
    ip: true

views:
  suffix: 'ejs'

security:
  contentSecurityPolicy: false
  cors:
    origin: "*"

typeorm:
  type: mysql
  host: 106.14.147.173
  port: 3306
  database: poppy
  username: root
  password: example
  maxQueryExecutionTime: 10000
  logging:
    - error
    - query

log4js:
  appenders:
    out:
      type: 'stdout'
  categories:
    default:
      appenders:
        - 'out'
      level: 'all'

mail:
  host: "smtp.163.com"
  port: 25
  secure: false
  auth:
    user: xxxxx@xx.com
    pass: 'xxx'
