# https://sergiodxa.com/articles/github-actions-npm-publish
# https://github.com/marketplace/actions/get-release-notes
name: CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    if: "startsWith(github.event.head_commit.message, 'chore(release):')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - name: Parse Version From Commit Message
      id: parse-version
      run: |
        ReleaseVer=`echo "${{ github.event.head_commit.message }}" | awk -F' ' '{print $2}'`
        echo "::set-output name=RELEASE_VERSION::${ReleaseVer: 1}"
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: echo "The job commit message ${{ github.event.head_commit.message }}."
    - run: npm ci
    - run: npm run lint
    - run: npm test
      env:
        TEST_COVERAGE_THRESHOLD: 0
        CI: true
    - run: npm run build --if-present
    - uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
