# https://sergiodxa.com/articles/github-actions-npm-publish
# https://github.com/marketplace/actions/get-release-notes
name: CD

on:
  push:
    branches: [ main ]

jobs:

  build:
    if: "startsWith(github.event.head_commit.message, 'chore(release):')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: echo "The job commit message ${{ github.event.head_commit.message }}."
    - run: npm ci
    - run: npm run lint
    - run: npm test
      env:
        TEST_COVERAGE_THRESHOLD: 0
        CI: true
    - run: npm run build --if-present
    - uses: actions/upload-artifact@v2
      with:
        name: poppy-server-dist
        path: dist
        retention-days: 5

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: poppy-server-dist
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            docker.pkg.github.com/${{ github.repository }}/poppy-server:${{ github.sha }}
            docker.pkg.github.com/${{ github.repository }}/poppy-server:${{ github.ref }}
